{% set name = "edt" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d65004ca21bdeacd7168070a9b581fd9c449e9063397540c22bc5a9aaec3874e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pbr
    - pip
    - python
    - cython
    - numpy
    - setuptools
  run:
    - python

test:
  imports:
    - edt

about:
  home: https://github.com/seung-lab/euclidean-distance-transform-3d
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Euclidean distance transform for multi-label 3D anisotropic images.
  description: Compute the Euclidean Distance Transform of a 1d, 2d, or 3d labeled image containing multiple labels in a single pass with support for anisotropic dimensions.

  doc_url: https://github.com/seung-lab/euclidean-distance-transform-3d
  dev_url: https://github.com/seung-lab/euclidean-distance-transform-3d

extra:
  recipe-maintainers:
    - william-silversmith
    - stuarteberg
