{% set name = "edt" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3696e1f7de482465af731a734a31b261a8852df8d583118f1b223d61764e063f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - pbr
    - pip
    - python
    - cython <3
    - numpy >=1.16.0
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - edt

about:
  home: https://github.com/seung-lab/euclidean-distance-transform-3d
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Euclidean distance transform for multi-label 3D anisotropic images.
  description: Compute the Euclidean Distance Transform of a 1d, 2d, or 3d labeled image containing multiple labels in a single pass with support for anisotropic dimensions.

  doc_url: https://github.com/seung-lab/euclidean-distance-transform-3d
  dev_url: https://github.com/seung-lab/euclidean-distance-transform-3d

extra:
  recipe-maintainers:
    - william-silversmith
