{% set name = "edt" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5dd6d5ce25e53eda113b43a7942c108747be8d5de352b1a90c3dcdfc465440e3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pbr
    - pip
    - python
    - numpy >=1.16.0
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - edt

about:
  home: https://github.com/seung-lab/euclidean-distance-transform-3d
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Euclidean distance transform for multi-label 3D anisotropic images.
  description: Compute the Euclidean Distance Transform of a 1d, 2d, or 3d labeled image containing multiple labels in a single pass with support for anisotropic dimensions.

  doc_url: https://github.com/seung-lab/euclidean-distance-transform-3d
  dev_url: https://github.com/seung-lab/euclidean-distance-transform-3d

extra:
  recipe-maintainers:
    - william-silversmith
